[package]
name = "taskscheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
typetag = "0.2.19"
warp = "0.3.7"
